# Generated by Django 3.1 on 2020-12-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSixColonneSYSCohada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='ControleEntreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dirigeants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('qualite', models.CharField(max_length=255)),
                ('numIdentificationFiscale', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EtatSalaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='FicheEffectif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnelPropre', models.FileField(upload_to='documents/')),
                ('personnelExterieur', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='FicheVersementAccompteIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='FicheVersementSpontaneIRPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='FicheVerSementTVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='FormeJuridique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forme', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MembreConseil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('qualite', models.CharField(max_length=255)),
                ('numIdentificationFiscale', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegimeFiscale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomService', models.CharField(max_length=255)),
                ('coutService', models.CharField(max_length=255)),
                ('delai', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConseil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
                ('dateSoumission', models.DateTimeField(auto_now_add=True)),
                ('etat', models.BooleanField(default=False)),
                ('paye', models.BooleanField(default=False)),
                ('objetService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gendsf.service')),
            ],
        ),
        migrations.CreateModel(
            name='InformationsAutres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAdresseQualite', models.CharField(max_length=255)),
                ('nomProfessionnel', models.CharField(max_length=255)),
                ('nomAdresseCommissaireCompte', models.CharField(max_length=255)),
                ('nomSignataireEtatsFinanciers', models.CharField(max_length=255)),
                ('qualiteSignataire', models.CharField(max_length=255)),
                ('dirigeants', models.ManyToManyField(related_name='informations', to='gendsf.Dirigeants')),
                ('membresConseil', models.ManyToManyField(related_name='informations', to='gendsf.MembreConseil')),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominationSociale', models.CharField(max_length=255)),
                ('sigleUsuel', models.CharField(max_length=255)),
                ('adresseComplete', models.CharField(blank=True, max_length=255, null=True)),
                ('boitePostale', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('telecopie', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('controleEntreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gendsf.controleentreprise')),
                ('formeJuridique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gendsf.formejuridique')),
            ],
        ),
        migrations.CreateModel(
            name='FicheFiscale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numIdentificationFiscale', models.CharField(max_length=255)),
                ('greffe', models.CharField(max_length=255)),
                ('sigleUsuel', models.CharField(max_length=255)),
                ('rccm', models.CharField(max_length=255)),
                ('numCodeImportateur', models.CharField(max_length=255)),
                ('numCaisseSociale', models.CharField(max_length=255)),
                ('dateDebutExercice', models.DateField()),
                ('dateArretComptes', models.DateField()),
                ('dateFinExercice', models.DateField()),
                ('republique', models.CharField(max_length=255)),
                ('ministere', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('centre', models.CharField(max_length=255)),
                ('regimeFiscale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gendsf.regimefiscale')),
            ],
        ),
        migrations.CreateModel(
            name='DSF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSoumission', models.DateTimeField(auto_now_add=True)),
                ('etat', models.BooleanField(default=False)),
                ('paye', models.BooleanField(default=False)),
                ('balanceSixColonneSYSCohada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gendsf.balancesixcolonnesyscohada')),
                ('ficheEffectif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gendsf.ficheeffectif')),
                ('ficheFiscale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gendsf.fichefiscale')),
                ('ficheVersementAccompteIS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gendsf.ficheversementaccompteis')),
                ('ficheVersementTVA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gendsf.ficheversementtva')),
                ('identification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gendsf.identification')),
                ('informationsAutres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gendsf.informationsautres')),
            ],
        ),
        migrations.CreateModel(
            name='DADS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSoumission', models.DateTimeField(auto_now_add=True)),
                ('etat', models.BooleanField(default=False)),
                ('paye', models.BooleanField(default=False)),
                ('etatsSalaires', models.ManyToManyField(related_name='dads', to='gendsf.EtatSalaire')),
                ('ficheFiscale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gendsf.fichefiscale')),
                ('identification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gendsf.identification')),
            ],
        ),
    ]
