# Generated by Django 3.1 on 2020-12-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gendsf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichefiscale',
            name='sigleUsuel',
        ),
    ]
