# Generated by Django 3.1 on 2020-12-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gendsf', '0003_auto_20201223_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsf',
            name='ficheEffectif',
        ),
        migrations.AddField(
            model_name='dads',
            name='ficheVersementSpontaneIRPP',
            field=models.FileField(null=True, upload_to='versements/'),
        ),
        migrations.AddField(
            model_name='dsf',
            name='personnelExterieur',
            field=models.FileField(null=True, upload_to='ficheeffectif/'),
        ),
        migrations.AddField(
            model_name='dsf',
            name='personnelPropre',
            field=models.FileField(null=True, upload_to='ficheeffectif/'),
        ),
        migrations.AlterField(
            model_name='dsf',
            name='balanceSixColonneSYSCohada',
            field=models.FileField(null=True, upload_to='syscohoda/'),
        ),
        migrations.AlterField(
            model_name='dsf',
            name='ficheVersementAccompteIS',
            field=models.FileField(null=True, upload_to='is/'),
        ),
        migrations.AlterField(
            model_name='dsf',
            name='ficheVersementTVA',
            field=models.FileField(null=True, upload_to='tva/'),
        ),
    ]
