# Generated by Django 3.1 on 2021-02-09 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gendsf', '0005_auto_20210208_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsf',
            name='infos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gendsf.informationsautres'),
        ),
    ]
