# Generated by Django 3.1 on 2020-11-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionlicence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='licence_key',
        ),
        migrations.AddField(
            model_name='devicetype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='pack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionlicence.package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
