# Generated by Django 3.1 on 2020-11-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionlicence', '0003_auto_20201112_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='user',
        ),
    ]
