# Generated by Django 3.0.3 on 2020-11-13 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionlicence', '0007_auto_20201112_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence', to='gestionlicence.Package'),
        ),
    ]
