# Generated by Django 3.1 on 2020-11-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionlicence', '0009_package_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='archive',
            field=models.FileField(default=1, upload_to='archives'),
            preserve_default=False,
        ),
    ]
