# Generated by Django 3.1 on 2021-02-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionlicence', '0010_application_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
