# Generated by Django 3.1 on 2021-02-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarifDouanier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(max_length=12)),
                ('libelleNomenclature', models.CharField(max_length=255)),
                ('quotite', models.IntegerField()),
                ('uniteStatistique', models.CharField(max_length=255)),
            ],
        ),
    ]
