# Generated by Django 3.1 on 2021-02-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulateur', '0002_auto_20210210_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifdouanier',
            name='nomenclature',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
