# Generated by Django 3.1 on 2021-03-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulateur', '0004_tarifdouanier_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifdouanier',
            name='dacc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarifdouanier',
            name='exhonereTVA',
            field=models.BooleanField(default=False),
        ),
    ]
