# Generated by Django 3.1 on 2021-03-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulateur', '0005_auto_20210303_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=255, unique=True)),
                ('valeur', models.FloatField(default=18)),
            ],
        ),
    ]
