# Generated by Django 3.1 on 2021-03-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulateur', '0006_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifdouanier',
            name='dacc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tarifdouanier',
            name='quotite',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tarifdouanier',
            name='ts',
            field=models.FloatField(default=0),
        ),
    ]
