# Generated by Django 3.1 on 2021-03-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulateur', '0008_devise_modepaiement_moyentransport_pays_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='devise',
            name='valeurDevise',
            field=models.IntegerField(default=0),
        ),
    ]
