# Generated by Django 3.1 on 2021-03-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulateur', '0012_auto_20210315_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimeFiscale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='regimeFiscale',
        ),
        migrations.AddField(
            model_name='simulation',
            name='regime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulateur.regimefiscale'),
        ),
    ]
