# Generated by Django 3.1 on 2021-03-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulateur', '0014_simulation_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='africa',
            field=models.BooleanField(default=False),
        ),
    ]
