# Generated by Django 3.1 on 2021-03-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulateur', '0015_pays_africa'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimeDouanier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(max_length=255, unique=True)),
                ('tauxImposition', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='regimefiscale',
            name='tauxImposition',
            field=models.FloatField(default=0),
        ),
    ]
