# Generated by Django 3.1 on 2021-03-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulateur', '0016_auto_20210323_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='modepaiement',
            name='code',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='code',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='regimedouanier',
            name='code',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
