# Generated by Django 3.1 on 2021-03-24 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulateur', '0017_auto_20210323_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('quotiteFixe', models.FloatField(default=0)),
                ('valeurForfaitaire', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaxeRegimeFiscale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotiteFixe', models.FloatField(default=0)),
                ('valeurForfaitaire', models.FloatField(default=0)),
                ('regime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulateur.regimefiscale')),
                ('taxe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulateur.taxe')),
            ],
        ),
        migrations.CreateModel(
            name='TaxeRegimeDouanier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotiteFixe', models.FloatField(default=0)),
                ('valeurForfaitaire', models.FloatField(default=0)),
                ('regime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulateur.regimedouanier')),
                ('taxe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulateur.taxe')),
            ],
        ),
        migrations.AddField(
            model_name='taxe',
            name='mes_regimes_douaniers',
            field=models.ManyToManyField(related_name='mes_taxes_doaunieres', through='simulateur.TaxeRegimeDouanier', to='simulateur.RegimeDouanier'),
        ),
        migrations.AddField(
            model_name='taxe',
            name='mes_regimes_fiscaux',
            field=models.ManyToManyField(related_name='mes_taxes_fiscales', through='simulateur.TaxeRegimeFiscale', to='simulateur.RegimeFiscale'),
        ),
    ]
